# Use a Node.js base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy the dependency files into the container
COPY package*.json ./

# Install the project dependencies
RUN npm ci

# Copy the Vite configuration file
COPY vite.config.js ./

# Copy the rest of the frontend code into the container
COPY . .

# Expose port 4000
EXPOSE 4000

# Command to start the development server
CMD ["npm", "run", "dev"]
